//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Protozoo.Dal.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Protozoo.Dal.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El parámetro {0} no puede nulo/vacío..
        /// </summary>
        internal static string Error_ArgumentNullException {
            get {
                return ResourceManager.GetString("Error_ArgumentNullException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en el proceso {0}.
        /// </summary>
        internal static string Error_GenericoProcedimientoAlmacenado {
            get {
                return ResourceManager.GetString("Error_GenericoProcedimientoAlmacenado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al convertir el valor: {0}.
        /// </summary>
        internal static string Error_InvalidCastException {
            get {
                return ResourceManager.GetString("Error_InvalidCastException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en la base de datos: &apos;{0}&apos;.
        /// </summary>
        internal static string Error_InvalidOperationException {
            get {
                return ResourceManager.GetString("Error_InvalidOperationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La página solicitada es mayor que el rango permitido..
        /// </summary>
        internal static string Error_MasRegistrosDeLosDebidos {
            get {
                return ResourceManager.GetString("Error_MasRegistrosDeLosDebidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El valor de {0} es nulo.
        /// </summary>
        internal static string Error_NullReferenceException {
            get {
                return ResourceManager.GetString("Error_NullReferenceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error al ejecutar el procedimiento almacenado &apos;{0}&apos; en {1}. Código: &apos;{2}&apos;, Descripción: &apos;{3}&apos;..
        /// </summary>
        internal static string Error_ProcedimientoAlmacenado {
            get {
                return ResourceManager.GetString("Error_ProcedimientoAlmacenado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error en la base de datos: &apos;{0}&apos;.
        /// </summary>
        internal static string Error_SQLException {
            get {
                return ResourceManager.GetString("Error_SQLException", resourceCulture);
            }
        }
    }
}
